sudo: false
language: python
python:
  - "2.7"
  - "3.6"
install: pip install flake8 tox-travis
before_script: flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
script: tox
